Make the clippy CI script fail on errors, and fix the clippy errors
Since the workspace split, scripts/run_clippy.sh runs one cargo clippy
invocation per workspace, but without `set -e` only the exit status of
the last invocation reached CI. Add `set -e` and fix the errors that
went unnoticed:

```
error: this block may be rewritten with the `?` operator
    --> internal/compiler/llr/lower_layout_expression.rs:2024:5
error: this block may be rewritten with the `?` operator
    --> internal/compiler/llr/lower_layout_expression.rs:2058:5
error: unneeded `return` statement
   --> internal/compiler/object_tree/interfaces.rs:312:5
error: useless conversion to the same type: `std::string::String`
   --> internal/compiler/object_tree/interfaces.rs:474:9
error: this `if` statement can be collapsed
   --> internal/core/item_tree.rs:425:13
error: local variable doesn't need to be boxed here
  --> internal/compiler/passes/remove_return.rs:76:5
error: local variable doesn't need to be boxed here
  --> internal/compiler/passes/remove_return.rs:75:5
error: local variable doesn't need to be boxed here
   --> internal/compiler/passes/remove_return.rs:141:5
error: this `if` statement can be collapsed
   --> internal/backends/winit/winitwindowadapter.rs:502:9
error: useless use of `format!`
   --> docs/slint-doc-generator/traceability.rs:334:33
```