Prospective CI fix
This is the error and I suspect it might be caused by nightly Rust

```
error: linking with `cc` failed: exit status: 1
    |
    = note:  "cc" "-m64" "<2 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/tmp/rustcwkmGMe/{liblibmimalloc_sys-005f094fef97aac1,libzstd_sys-c8aab6a275cf0406,libring-909ac6f5b832739f}.rlib" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-*.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/tmp/rustcwkmGMe/raw-dylibs" "-B<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-fuse-ld=lld" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/tmp/cargo-install3BVRG4/release/build/zstd-sys-779651c9ffdf85a9/out" "-L" "/tmp/cargo-install3BVRG4/release/build/ring-4cfab80d71b7fa5c/out" "-L" "/tmp/cargo-install3BVRG4/release/build/libmimalloc-sys-2dbea4f52bdeade9/out" "-L" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-install3BVRG4/release/deps/cargo_about-802b7704a384375e" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-debug" "-nodefaultlibs"
    = note: some arguments are omitted. use `--verbose` to show all linker arguments
    = note: rust-lld: error: undefined hidden symbol: __rustc::__rg_oom
            >>> referenced by 8zaj4jr8xznft4fdfgvxj4tj7
            >>>               /tmp/cargo-install3BVRG4/release/deps/cargo_about-802b7704a384375e.8zaj4jr8xznft4fdfgvxj4tj7.rcgu.o:(__rustc::__rust_alloc_error_handler)
            collect2: error: ld returned 1 exit status

  error: could not compile `cargo-about` (bin "cargo-about") due to 1 previous error
```