compiler: interface errors include notes pointing to the conflicting declaration
This is a combination of 10 commits:

compiler: `validate_interface_member_implementation` doesn't generate missing member error

The error is already generated in `property_matches_interface`. DRY.

compiler: validate_interface_member_implementation now adds notes on conflicting statements

Previously this function only added notes for local declarations. Now we
can use Element::property_declaration_node to get the declaration on the
inherited node that causes the problem.

compiler: add interfaces::validate_interface_implementation

This is a private function that is used by both public functions
`validate_self_implement_statements` and
`apply_child_implement_statements`. This means that the interface
validation logic for an element is consolidated into one path. As a
consequence, the `apply_child_implement_statements` path now emits notes
for declarations that conflict with an interface.

compiler: interface::apply_child_implement_statements adds notes for conflicts on base components

Emit a note on the base component when a declaration in the base
component does not satisfy the interface in an `implement Interface <=>
child-id;` statement.

compiler: emit notes when a declaration conflicts with a child-implemented interface

Add a note that highlights where the conflict comes from. We end up with
multiple notes because we want one per "Cannot override" error:

```
error: Cannot override 'reset' from 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:163:26
    |
163 |     public pure function reset() {}
    |                          ^^^^^
note: 'ValidInterface' declares 'pure public function reset() { }'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:153:15
    |
153 |     implement ValidInterface <=> base;
    |               ^^^^^^^^^^^^^^^
error: Cannot override 'speak' from 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:161:14
    |
161 |     callback speak();
    |              ^^^^^
note: 'ValidInterface' declares 'callback speak();'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:153:15
    |
153 |     implement ValidInterface <=> base;
    |               ^^^^^^^^^^^^^^^
error: Cannot override 'value' from 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:159:27
    |
159 |     in-out property <int> value;
    |                           ^^^^^
note: 'ValidInterface' declares 'in-out property <int> value;'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:153:15
    |
153 |     implement ValidInterface <=> base;
    |
```

compiler: apply_child_implement_statements emits more specific notes

The source now highlights the syntax that is incorrect, and the note
says what the interface declares. Coupled with the actual error message,
this should give the user the full picture of what the error is, where
the error originates and where to apply the fix.

In order to find the correct source location for the diagnostic we have
to hunt through the syntax nodes to find an identifier with the expected
keyword, as the SyntaxNodes do not provide enough granularity to extract
visibility or purity directly. If we can't find the expected anchor we
try to fall back to the name identifier, and worst case we refer to the
whole declaration (which does not happen in practise).

One side effect is that duplicate notes can be a bit repetitive:

```
error: Cannot implement 'OutOnlyInterface'.
       - 'count' must be a 'int' property (found a 'float' property)
       - 'count' must be 'out' (found 'in-out')
   --> internal/compiler/tests/syntax/interfaces/implement_self.slint:286:15
    |
286 |     implement OutOnlyInterface <=> self;
    |               ^^^^^^^^^^^^^^^^^
note: 'OutOnlyInterface' declares 'count' as 'out property <int> count;'
   --> internal/compiler/tests/syntax/interfaces/implement_self.slint:289:22
    |
289 |     in-out property <float> count;
    |                      ^^^^^
note: 'OutOnlyInterface' declares 'count' as 'out property <int> count;'
   --> internal/compiler/tests/syntax/interfaces/implement_self.slint:289:5
    |
289 |     in-out property <float> count;
    |     ^^^^^^
```

We considered having one "'Interface' declares 'member' as" error and
having multiple more specific notes, but the notes are not currently
visible in the IDE.

compiler: refactor syntax_for_declaration from syntax for

This allows us to add `syntax_for_lookup_result` in a future commit. We
want to compare the syntax for PropertyDeclaration and
PropertyLookupResult. This allows us to re-use the display code.

compiler: interfaces::syntax_for re-uses the Display implementation for Function

Now that it doesn't print the void return type we can use it directly,
instead of re-implementing it.

compiler: interfaces::property_matches_interface uses full syntax for functions and callbacks

This means we don't get the `function() -> void` output for void
returning callbacks/functions.

compiler: remove static keyword list from interfaces.rs

The list of static strings is likely to get out-of-date. Instead, we
capture the PropertyVisibility to find in the
DeclarationAnchor::Visibility variant and match on the display string it
returns. We must take care to normalize `_` to `-`.

compiler: remove `check_property_declaration_conflicts` from `validate_interface_member_implementation`

This doesn't change the number of errors reported, just the error
message we get. The new message is more specific, containing the actual
issue with the conflict (e.g. wrong property type) rather than just
saying "there is a conflict".

This also simplifies the implementation of
`validate_interface_member_implementation`.