codegen: Don't generate unused struct
This fixes a warning in nightly rust which has been better at detecting
unused struct

```
error: struct `TextStyle` is never constructed
  --> /home/runner/work/slint/slint/target/debug/build/slint-lsp-da851cbad8b87459/out/main.rs:78:66
   |
78 |      # [derive (Default , PartialEq , Debug , Clone)] pub struct r#TextStyle {
   |                                                                  ^^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(dead_code)]`
```

Where TextStyle is only used in some globals whose properties are fully
inlined. So first do the pass that removed unused global, and then the
pass that remove unused struct