compiler: correctly position interface note diagnostics after errors
Before we were emitting notes before the relevant errors which was not
very useful when looking at `slint-compiler` output. Now we emit the
notes after the error, giving us more understandable compiler output:

```
error: Cannot implement 'ValidInterface'.
       - 'reset' must be a 'public function() -> void' (found a 'int' property)
       - 'speak' must be a 'callback() -> void' (found a 'int' property)
       - 'value' must be an in-out 'int' property (found a 'callback() -> void')
   --> internal/compiler/tests/syntax/interfaces/implement_self.slint:255:15
    |
255 |     implement ValidInterface <=> self;
    |               ^^^^^^^^^^^^^^^
note: 'reset' does not satisfy 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_self.slint:262:5
    |
262 |     in-out property <int> reset;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: 'speak' does not satisfy 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_self.slint:260:5
    |
260 |     in-out property <int> speak;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: 'value' does not satisfy 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_self.slint:258:5
    |
258 |     callback value();
    |     ^^^^^^^^^^^^^^^^^
```