CI: prospective fix of the build by setting the Python version
Python recently was updated to 3.11 and the build of the node binding is
now failing.
(Apparently still using a quite old version of node-gyp, because this
was fixed in `https://github.com/nodejs/node-gyp/issues/2219`)

```
     File "/home/runner/work/slint/slint/target/debug/build/neon-sys-4b140f4af6e7aeb3/out/native/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
      build_file_contents = open(build_file_path, "rU").read()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ValueError: invalid mode: 'rU' while trying to load binding.gyp
```