Revert "linuxkms: Update drm and gbm dependencies"
This reverts commit 17afe1aa8ac4c730a2025b30f7d5c32b3799632b.

This causes

 thread '<unnamed>' panicked at 'assertion failed: (has_modifier && modifier.is_some()) || (!has_modifier && modifier.is_none())', drm-0.10.0/src/control/mod.rs:324:9

when running on qemu-virgl.