Fix cross_compile_check CI job
commit 1a44bc881455714f12b583b65cad8e368b982208 added the
slint/software-renderer-path feature to one of the job but wasn't tesed
with `--cfg slint_int_coord` before

```
error[E0277]: cannot add `Vector2D<i32, LogicalPx>` to `Point2D<f32, _>`
   --> /home/runner/work/slint/slint/internal/core/graphics/path.rs:341:19
    |
341 |         Some((pos + self.offset, angle))
    |                   ^ no implementation for `Point2D<f32, _> + Vector2D<i32, LogicalPx>`
```