Prospective CI fix:
```
 error: unnecessary `unsafe` block
   --> examples/mcu-board-support/stm32h735g.rs:209:26
    |
209 |         let (fb1, fb2) = unsafe { (core::ptr::addr_of!(FB1), core::ptr::addr_of!(FB2)) };
    |                          ^^^^^^ unnecessary `unsafe` block
    |
    = note: `-D unused-unsafe` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unused_unsafe)]`
```

(probably caused by the recent Rust release)