Prospective fix for the test on MSVC
The CI gets the error

```
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): error C2665: 'Color::Color': no overloaded function could convert all the argument types
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: could be 'Color::Color(Color &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: 'Color::Color(Color &&)': cannot convert argument 1 from 'slint::SharedString' to 'Color &&'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: Reason: cannot convert from 'slint::SharedString' to 'Color'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: or       'Color::Color(const Color &)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: 'Color::Color(const Color &)': cannot convert argument 1 from 'slint::SharedString' to 'const Color &'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: Reason: cannot convert from 'slint::SharedString' to 'const Color'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: while trying to match the argument list '(slint::SharedString)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(11): note: This diagnostic occurred in the compiler generated function 'Color::Color(Color &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(140): note: see reference to function 'Color::Color(Color &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(140): note: see reference to function template instantiation 'Color TestCase::init::<lambda_2>::operator ()<std::tuple<slint::SharedString>>(const _T1 &) const' being compiled
        with
        [
            _T1=std::tuple<slint::SharedString>
        ]
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): error C3511: 'SharedString': a call to a delegating constructor shall be the only member-initializer
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: This diagnostic occurred in the compiler generated function 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(147): note: see reference to function 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(148): note: see reference to function template instantiation 'SharedString TestCase::init::<lambda_4>::()::<lambda_1>::operator ()<slint::SharedString,slint::SharedString,int>(const _T1 &,const _T2 &,const _T3 &) const' being compiled
        with
        [
            _T1=slint::SharedString,
            _T2=slint::SharedString,
            _T3=int
        ]
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): error C2665: 'SharedString::SharedString': no overloaded function could convert all the argument types
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: could be 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: 'SharedString::SharedString(SharedString &&)': cannot convert argument 1 from 'slint::SharedString' to 'SharedString &&'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: Reason: cannot convert from 'slint::SharedString' to 'SharedString'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: or       'SharedString::SharedString(const SharedString &)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: 'SharedString::SharedString(const SharedString &)': cannot convert argument 1 from 'slint::SharedString' to 'const SharedString &'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: Reason: cannot convert from 'slint::SharedString' to 'const SharedString'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: while trying to match the argument list '(slint::SharedString)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: This diagnostic occurred in the compiler generated function 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(147): note: see reference to function 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): error C2437: 'Component': has already been initialized
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: This diagnostic occurred in the compiler generated function 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(147): note: see reference to function 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): error C2437: 'Model': has already been initialized
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(31): note: This diagnostic occurred in the compiler generated function 'SharedString::SharedString(SharedString &&)'
C:\Users\RUNNER~1\AppData\Local\Temp\.tmpUISeUr.cpp(147): note: see reference to function 'SharedString::SharedString(SharedString &&)'
```

Which I don't feel like debugging now

(cherry picked from commit 9fec9992b4ab87ae32d2116264086a19b3d3d029)