CI: prospective fix to flacky esp-idf build
``` 
[warn]: Failed to get latest Xtensa Rust version: HTTP GET Error: GitHub API returned status code: 403 Forbidden
Error: espup::toolchain::http_error

  × HTTP GET Error: GitHub API returned status code: 403 Forbidden
``` 

Presumably because the github action hits rate limit.
Using a github token might help.

Add GITHUB_TOKEN environment variable to CI workflow