Fix license header check on napi/.npmignore
Fixes

Error: checking /Users/simon/src/slint/api/napi/.npmignore

Caused by:
    Cannot determine the expected license header style. Please fix the license checking xtask.