compiler: emit notes when a declaration conflicts with a child-implemented interface
Add a note that highlights where the conflict comes from. We end up with
multiple notes because we want one per "Cannot override" error:

```
error: Cannot override 'reset' from 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:163:26
    |
163 |     public pure function reset() {}
    |                          ^^^^^
note: 'ValidInterface' declares 'pure public function reset() { }'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:153:15
    |
153 |     implement ValidInterface <=> base;
    |               ^^^^^^^^^^^^^^^
error: Cannot override 'speak' from 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:161:14
    |
161 |     callback speak();
    |              ^^^^^
note: 'ValidInterface' declares 'callback speak();'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:153:15
    |
153 |     implement ValidInterface <=> base;
    |               ^^^^^^^^^^^^^^^
error: Cannot override 'value' from 'ValidInterface'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:159:27
    |
159 |     in-out property <int> value;
    |                           ^^^^^
note: 'ValidInterface' declares 'in-out property <int> value;'
   --> internal/compiler/tests/syntax/interfaces/implement_child.slint:153:15
    |
153 |     implement ValidInterface <=> base;
    |
```