Remove `doc_auto_cfg` feature
Rust nightly removed this:

```
error[E0557]: feature has been removed
 --> internal/interpreter/lib.rs:4:38
  |
4 | #![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
  |                                      ^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
  = note: merged into `doc_cfg`

```