Workaround panic of autocompletion of import with unicode
(As seen in the crash reporter)

Eg:
```
thread 'LanguageServer' panicked at tools/lsp/language/completion.rs:731:17:
byte index 4 is not a char boundary; it is inside '🍒' (bytes 2..6) of `./🍒🍓🍇"`
```

This can happen because offset might not be on a char boundary because
of the utf-16 / utf-8 mismatch.