LinuxKMS:  Fix a compilation issue for combination of wgpu-29 and renderer-skia-vulkan (#11986)
Use wgpu-29 instead of 27 for wgpu_surface

It fails due to missing methods:
```
error[E0599]: no method named `find_compatible_plane` found for reference `&DrmOutput` in the current scope
error[E0599]: no method named `refresh_rate_millihertz` found for reference `&DrmOutput` in the current scope
```
since the `wgpu_surface` configuration still requires **wgpu-27** and 28. But it should be **wgpu-29** instead of 27.