CI: manually exclude slint-cpp
Otherwise, since the recent introduction of esp-backtrace, the CI fails
with

```
error: failed to run custom build command for `esp-println v0.5.0`
[...]
  thread 'main' panicked at 'Exactly 1 chip must be enabled via its Cargo feature, 0 provided', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-println-0.5.0/build.rs:16:14
```

Because it is ran with --all-features and this enable the esp-backtrace crate but without enabling a specific chip.